INCLUDE= \
-I${SERVER_ROOT}/src/common \
-I${SERVER_ROOT}/src/task \
-I${SERVER_ROOT}/src/main \
-I${SERVER_ROOT}/src/command
LIBS= \
-L/usr/local/lib \
-lpthread \
-Wl,-rpath,../libs
CFLAGS = -g -Wall -D_REENTRANT -D__USE_EPOLL 
