all:
	cd common;make;cd ..
	cd main;make;cd ..
	cd test;make;cd ..
install:
	cd common;make install;cd ..
	cd main;make install;cd ..
	cd test;make install;cd ..
clean:
	make -f makeobj clean;
	cd common;make clean;cd ..
	cd main;make clean;cd ..
	cd test;make clean;cd ..
